# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84f65d772d17c72bb24a175068201a686f27761b903af64ffd926ff5276f13f212d52ffae8e13b2edce66a2c65a10af887e08e1f331db7a01ae02926741b0fd5

test:
  secret_key_base: 8edeaa9c937017fef65cb5a274a388e0abfd89e001ca7ef74c41d62d284b069a95caf2f3e5a77e908ce91b010ff4d6daa7e450f7744b5f68afa9a118f1e27e87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
